/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package solverde;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import solverde.SolarCalculator;
import solverde.RoofDetails;
import solverde.SolarPanel;
import javax.swing.JOptionPane;
import java.io.FileWriter;
import java.io.FileReader;
import java.io.IOException;
import java.io.BufferedReader;
import java.util.ArrayList;


/**
 *
 * @author henry
 */
public class SolarCalcGUI extends javax.swing.JFrame {
   private ArrayList<String> results = new ArrayList<>();
   
 
    public SolarCalcGUI() {
        initComponents();
    }
    
    // save calculation
    public void saveCalculation(String calculation) {
        results.add(calculation); // Save calculation to memory
        System.out.println(calculation); // Print to console
        JOptionPane.showMessageDialog(this, "Calculation saved!");
    }

    // Method to load the saved calculations
    public void loadCalculation() {
        if (results.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No calculations found!");
        } else {
            StringBuilder allCalculations = new StringBuilder("Saved Calculations:\n");
            for (String calc : results) {
                allCalculations.append(calc).append("\n");
            }
            JOptionPane.showMessageDialog(this, allCalculations.toString());
        }
    }

         
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SolarCalcBackPanel = new javax.swing.JPanel();
        SolarCalcTitle = new javax.swing.JLabel();
        RoofSizeLabel = new javax.swing.JLabel();
        LocationLabel = new javax.swing.JLabel();
        RoofDirectionLabel = new javax.swing.JLabel();
        SunlightLabel = new javax.swing.JLabel();
        PanelNumberLabel = new javax.swing.JLabel();
        calculateButton = new javax.swing.JButton();
        LocationSelector = new javax.swing.JComboBox<>();
        RoofDimensionInput = new javax.swing.JTextField();
        RoofOrientation = new javax.swing.JComboBox<>();
        SunlightExposureSlider = new javax.swing.JSlider();
        noOfPanels = new javax.swing.JComboBox<>();
        HomePage = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        SaveCalc = new javax.swing.JButton();
        LoadCalc = new javax.swing.JButton();
        EnergyEsitmateLabel = new javax.swing.JLabel();
        CO2Reduction = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        EnergyProductionOutput = new javax.swing.JTextField();
        CO2Output = new javax.swing.JTextField();
        CostSavingOutput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(392, 740));

        SolarCalcBackPanel.setBackground(new java.awt.Color(76, 181, 181));

        SolarCalcTitle.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 48)); // NOI18N
        SolarCalcTitle.setForeground(new java.awt.Color(255, 153, 51));
        SolarCalcTitle.setText("Solar Potential Calculator");

        RoofSizeLabel.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 24)); // NOI18N
        RoofSizeLabel.setText("Roof Size (sq. meters)");

        LocationLabel.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 24)); // NOI18N
        LocationLabel.setText("Location ");

        RoofDirectionLabel.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 24)); // NOI18N
        RoofDirectionLabel.setText("Roof Orientation");

        SunlightLabel.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 24)); // NOI18N
        SunlightLabel.setText("Sunlight Exposure ");

        PanelNumberLabel.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 24)); // NOI18N
        PanelNumberLabel.setText("Number of Panels");

        calculateButton.setBackground(new java.awt.Color(72, 211, 156));
        calculateButton.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 24)); // NOI18N
        calculateButton.setText("Calculate Potential");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        LocationSelector.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 24)); // NOI18N
        LocationSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Province", "Connaught", "Leinster", "Munster", "Ulster" }));
        LocationSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationSelectorActionPerformed(evt);
            }
        });

        RoofDimensionInput.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 24)); // NOI18N
        RoofDimensionInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoofDimensionInputActionPerformed(evt);
            }
        });

        RoofOrientation.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 24)); // NOI18N
        RoofOrientation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Garden Facing", "North (N)", "East (E)", "South (S)", "West (W)" }));
        RoofOrientation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoofOrientationActionPerformed(evt);
            }
        });

        noOfPanels.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 24)); // NOI18N
        noOfPanels.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desired Panels", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        HomePage.setBackground(new java.awt.Color(72, 211, 156));
        HomePage.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 30)); // NOI18N
        HomePage.setText("Home");
        HomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePageActionPerformed(evt);
            }
        });

        ResetBtn.setBackground(new java.awt.Color(72, 211, 156));
        ResetBtn.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 24)); // NOI18N
        ResetBtn.setText("Reset Input");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });

        SaveCalc.setBackground(new java.awt.Color(72, 211, 156));
        SaveCalc.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 24)); // NOI18N
        SaveCalc.setText("Save Calculation");
        SaveCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveCalcActionPerformed(evt);
            }
        });

        LoadCalc.setBackground(new java.awt.Color(72, 211, 156));
        LoadCalc.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 24)); // NOI18N
        LoadCalc.setText("Load Calculation");
        LoadCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadCalcActionPerformed(evt);
            }
        });

        EnergyEsitmateLabel.setBackground(new java.awt.Color(72, 211, 156));
        EnergyEsitmateLabel.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 22)); // NOI18N
        EnergyEsitmateLabel.setText("Estimated Energy Production (kWh/year) :");

        CO2Reduction.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 22)); // NOI18N
        CO2Reduction.setText("CO2 Reduction Estimate :");

        jLabel1.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 22)); // NOI18N
        jLabel1.setText("Cost Savings Estimate € :");

        EnergyProductionOutput.setEditable(false);
        EnergyProductionOutput.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 20)); // NOI18N
        EnergyProductionOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnergyProductionOutputActionPerformed(evt);
            }
        });

        CO2Output.setEditable(false);
        CO2Output.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 20)); // NOI18N
        CO2Output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CO2OutputActionPerformed(evt);
            }
        });

        CostSavingOutput.setEditable(false);
        CostSavingOutput.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 20)); // NOI18N
        CostSavingOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostSavingOutputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SolarCalcBackPanelLayout = new javax.swing.GroupLayout(SolarCalcBackPanel);
        SolarCalcBackPanel.setLayout(SolarCalcBackPanelLayout);
        SolarCalcBackPanelLayout.setHorizontalGroup(
            SolarCalcBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SolarCalcBackPanelLayout.createSequentialGroup()
                .addGroup(SolarCalcBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SolarCalcBackPanelLayout.createSequentialGroup()
                        .addComponent(HomePage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SolarCalcTitle))
                    .addGroup(SolarCalcBackPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(SolarCalcBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(SolarCalcBackPanelLayout.createSequentialGroup()
                                .addGroup(SolarCalcBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RoofSizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RoofDirectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SunlightLabel)
                                    .addComponent(PanelNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(SolarCalcBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(noOfPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(SolarCalcBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(LocationSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RoofDimensionInput)
                                        .addComponent(RoofOrientation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SunlightExposureSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                            .addGroup(SolarCalcBackPanelLayout.createSequentialGroup()
                                .addGroup(SolarCalcBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SaveCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(SolarCalcBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(calculateButton)
                                    .addComponent(LoadCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(SolarCalcBackPanelLayout.createSequentialGroup()
                                .addGroup(SolarCalcBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CO2Reduction, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(SolarCalcBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CO2Output, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CostSavingOutput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(SolarCalcBackPanelLayout.createSequentialGroup()
                                .addComponent(EnergyEsitmateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EnergyProductionOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        SolarCalcBackPanelLayout.setVerticalGroup(
            SolarCalcBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SolarCalcBackPanelLayout.createSequentialGroup()
                .addGroup(SolarCalcBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HomePage)
                    .addComponent(SolarCalcTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(SolarCalcBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SolarCalcBackPanelLayout.createSequentialGroup()
                        .addComponent(RoofDimensionInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LocationSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(RoofOrientation, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SunlightExposureSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SolarCalcBackPanelLayout.createSequentialGroup()
                        .addComponent(RoofSizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RoofDirectionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SunlightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SolarCalcBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelNumberLabel)
                    .addComponent(noOfPanels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SolarCalcBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateButton)
                    .addComponent(ResetBtn))
                .addGap(9, 9, 9)
                .addGroup(SolarCalcBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveCalc)
                    .addComponent(LoadCalc))
                .addGap(29, 29, 29)
                .addGroup(SolarCalcBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnergyEsitmateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnergyProductionOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SolarCalcBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CO2Reduction)
                    .addComponent(CO2Output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(SolarCalcBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CostSavingOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SolarCalcBackPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SolarCalcBackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LocationSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationSelectorActionPerformed

    private void RoofDimensionInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoofDimensionInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoofDimensionInputActionPerformed

    private void HomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePageActionPerformed
        //Adds the function to the home button to bring the user to the home page//
        mainGUI MainPageGUI = new mainGUI();
        MainPageGUI.setVisible(true);
        //closes the current page//
        this.dispose();
    }//GEN-LAST:event_HomePageActionPerformed

    private void CO2OutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CO2OutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CO2OutputActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        // TODO add your handling code here:
    calculateButton.addActionListener(event-> {
      try {
        //inputs from the GUI
        double roofSize = Double.parseDouble(RoofDimensionInput.getText());
        int panelCount = Integer.parseInt(noOfPanels.getSelectedItem().toString());
        String location = LocationSelector.getSelectedItem().toString(); // Provinces
        String roofOrientation = RoofOrientation.getSelectedItem().toString(); // Directions

        //instances of RoofDetails and SolarPanel
        RoofDetails roofDetails = new RoofDetails(roofSize, roofOrientation, 50, location); // Sunlight exposure fixed at 100% for simplicity
        SolarPanel solarPanel = new SolarPanel(panelCount, 18.0); // Efficiency: 18%

        //calculations using SolarCalculator
        SolarCalculator calculator = new SolarCalculator(roofDetails, solarPanel);
        double energyProduction = calculator.calculateEnergyProduction(); // energy in kWh/year
        double co2Reduction = calculator.calculateCO2Reduction(); // CO2 reduction in kg/year
        double costSavings = calculator.calculateCostSavings(0.12); // electricity rate €0.12/kWh

        //gui outputs
        EnergyProductionOutput.setText(String.format("%.2f kWh/year", energyProduction));
        CO2Output.setText(String.format("%.2f kg CO2/year", co2Reduction));
        CostSavingOutput.setText(String.format("€%.2f", costSavings));

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "Please fill in the required fields", "Input Error", JOptionPane.ERROR_MESSAGE);
    }
});







    }//GEN-LAST:event_calculateButtonActionPerformed

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
        ResetBtn.addActionListener(event -> {
    // clear input fields
    RoofDimensionInput.setText(""); 
    noOfPanels.setSelectedIndex(0); 
    LocationSelector.setSelectedIndex(0); 
    SunlightExposureSlider.setValue(5); 
    RoofOrientation.setSelectedIndex(0); 

    // clear output fields
    EnergyProductionOutput.setText("");
    CO2Output.setText("");
    CostSavingOutput.setText("");
});

 
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void EnergyProductionOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnergyProductionOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnergyProductionOutputActionPerformed

    private void SaveCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveCalcActionPerformed
           // takes user info from 3 fiedlds
    String input1 = EnergyProductionOutput.getText(); // Eenergy production
    String input2 = CO2Output.getText();             // CO2 output
    String input3 = CostSavingOutput.getText();      // cost savings

    // make sure none of outputs are empty
    if (input1.isEmpty() || input2.isEmpty() || input3.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields!");
        return;
    
    }//GEN-LAST:event_SaveCalcActionPerformed

         // format calcs
    String calculation = "Energy Production: " + input1 + ", CO2 Output: " + input2 + ", Cost Savings: " + input3;
        saveCalculation(calculation); // Save the user inputs
        
        // add string to arraylist
        results.add(calculation);
        JOptionPane.showMessageDialog(this, "Calculation saved!");
        
    }
    private void LoadCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadCalcActionPerformed
        loadCalculation();  //show saved calcs
        


    }//GEN-LAST:event_LoadCalcActionPerformed

    private void RoofOrientationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoofOrientationActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_RoofOrientationActionPerformed

    private void CostSavingOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostSavingOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostSavingOutputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SolarCalcGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SolarCalcGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SolarCalcGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SolarCalcGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SolarCalcGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CO2Output;
    private javax.swing.JLabel CO2Reduction;
    private javax.swing.JTextField CostSavingOutput;
    private javax.swing.JLabel EnergyEsitmateLabel;
    private javax.swing.JTextField EnergyProductionOutput;
    private javax.swing.JButton HomePage;
    private javax.swing.JButton LoadCalc;
    private javax.swing.JLabel LocationLabel;
    private javax.swing.JComboBox<String> LocationSelector;
    private javax.swing.JLabel PanelNumberLabel;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JTextField RoofDimensionInput;
    private javax.swing.JLabel RoofDirectionLabel;
    private javax.swing.JComboBox<String> RoofOrientation;
    private javax.swing.JLabel RoofSizeLabel;
    private javax.swing.JButton SaveCalc;
    private javax.swing.JPanel SolarCalcBackPanel;
    private javax.swing.JLabel SolarCalcTitle;
    private javax.swing.JSlider SunlightExposureSlider;
    private javax.swing.JLabel SunlightLabel;
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> noOfPanels;
    // End of variables declaration//GEN-END:variables
}
