/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package solverde;

/**
 *
 * @author danma
 */
public class InstallGuideGUI extends javax.swing.JFrame {
     //generate an array of objects containing the information displayed on the insallation guide
     InstallInfo[] info = {
         new InstallInfo("Before the installation of Solar Panels, you will need to prepare \n" +
"your home by removing any debris from your roof and ensuring\n" +
"that your roof hasn't sustained any damage or contains holes.\n" +
"You must also ensure that your electrical system is stable and\n" +
"your home is properly grounded."),
         new InstallInfo("Once you have ensured your roof is suitable for the installation of\n" +
"Solar Panels, the next step is to determine where is the best\n" +
"location on your home to install solar panels to ensure the best\n" +
"structural stability, the number of panels and the electricity you\n" +
"wish to produce should be taken into account."),
         new InstallInfo("There are three types of solar panels that SolVerde provides, thin\n" +
"film panels, mono cystalline panels, and poly crystalline panels.\n" +
"when considering what solar panels are right for you, take into \n" +
"account the energy efficiency, durability, lifespan and the cost."),
         new InstallInfo("Once you have considered all of the above information, it's time\n" +
"to install your solar panels. the panels will be attached to your roof\n" +
"and the elecrical wiring will connect the solar panels to your home\n" +
"electrical system. After installation, monitor your electrical system\n" +
"to ensure that the solar panels are working correctly, a monitoring\n" +
"system or phone app can be used to easily track this or any \n" +
"issues that may arise with the system.")
     };
    /**
     * Creates new form InstallGuideGUI
     */
    public InstallGuideGUI() {
        initComponents();
        initializeTextAreas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackDrop = new javax.swing.JPanel();
        HeadingLabel = new javax.swing.JLabel();
        HomePage = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mantinenceText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        installText = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        structuralText = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        selectionText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(76, 181, 181));

        BackDrop.setBackground(new java.awt.Color(76, 181, 181));

        HeadingLabel.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 48)); // NOI18N
        HeadingLabel.setForeground(new java.awt.Color(255, 153, 51));
        HeadingLabel.setText("Installation Guide");

        HomePage.setBackground(new java.awt.Color(72, 211, 156));
        HomePage.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 30)); // NOI18N
        HomePage.setText("Home Page");
        HomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePageActionPerformed(evt);
            }
        });

        jToggleButton1.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 24)); // NOI18N
        jToggleButton1.setText("Setting your house up for the installation of solar panels");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 24)); // NOI18N
        jToggleButton2.setText("Ensuring Structural Stability");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 24)); // NOI18N
        jToggleButton3.setText("Selecting the correct Solar Panel");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton4.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 24)); // NOI18N
        jToggleButton4.setText("Installation and Mantinence Advice");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        mantinenceText.setColumns(20);
        mantinenceText.setRows(5);
        mantinenceText.setText("Once you have considered all of the above information, it's time\nto install your solar panels. the panels will be attached to your roof\nand the elecrical wiring will connect the solar panels to your home\nelectrical system. After installation, monitor your electrical system\nto ensure that the solar panels are working correctly, a monitoring\nsystem or phone app can be used to easily track this or any \nissues that may arise with the system.");
        jScrollPane1.setViewportView(mantinenceText);

        installText.setColumns(20);
        installText.setRows(5);
        jScrollPane2.setViewportView(installText);

        structuralText.setColumns(20);
        structuralText.setRows(5);
        jScrollPane3.setViewportView(structuralText);

        selectionText.setColumns(20);
        selectionText.setRows(5);
        jScrollPane4.setViewportView(selectionText);

        javax.swing.GroupLayout BackDropLayout = new javax.swing.GroupLayout(BackDrop);
        BackDrop.setLayout(BackDropLayout);
        BackDropLayout.setHorizontalGroup(
            BackDropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackDropLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HomePage))
            .addGroup(BackDropLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(HeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackDropLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(BackDropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane4)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        BackDropLayout.setVerticalGroup(
            BackDropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackDropLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(HeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jToggleButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HomePage)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackDrop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackDrop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void initializeTextAreas(){
        //set visibility
        installText.setVisible(false);
        structuralText.setVisible(false);
        selectionText.setVisible(false);
        mantinenceText.setVisible(false);
    }
    
    //method to display coresponding text and hide others
    private void displayInfo(int index) {
        installText.setVisible(index == 0);
        structuralText.setVisible(index == 1);
        selectionText.setVisible(index == 2);
        mantinenceText.setVisible(index == 3);
    
    
    //update the contents of the visible textarea
    if(index == 0) {
    installText.setText(info[0].getInfo());
    } else if (index == 1) {
    structuralText.setText(info[1].getInfo());
    } else if (index == 2) {
    selectionText.setText(info[2].getInfo());
    } else if (index == 3) {
    mantinenceText.setText(info[3].getInfo());
    }
}
    
    private void HomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePageActionPerformed
        //Adds the function to the home button to bring the user to the home page//
        mainGUI MainPageGUI = new mainGUI();
        MainPageGUI.setVisible(true);
        //closes the current page//
        this.dispose();
    }//GEN-LAST:event_HomePageActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
       displayInfo(0);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
       displayInfo(1);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
       displayInfo(2);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        displayInfo(3);
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstallGuideGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstallGuideGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstallGuideGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstallGuideGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstallGuideGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackDrop;
    private javax.swing.JLabel HeadingLabel;
    private javax.swing.JButton HomePage;
    private javax.swing.JTextArea installText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JTextArea mantinenceText;
    private javax.swing.JTextArea selectionText;
    private javax.swing.JTextArea structuralText;
    // End of variables declaration//GEN-END:variables
}
